export const categories = [
  "Running Shoes",
  "Football",
  "Cricket Bat",
  "Yoga Mat",
  "Dumbbells",
  "Table Tennis",
  "Activewear",
  "Gym Bag",
];

// lib/allProducts.ts
import { Product } from "./type";

export const allProducts: Product[]= [
  {
    id: 1,
    name: "Colorful Sport Shirt",
    description: "A vibrant and breathable sport shirt perfect for workouts or casual wear.",
    price: "₹399",
    rating: 4.5,
    category: "Cricket Bat",
    imageSrc: "https://png.pngtree.com/png-vector/20240131/ourmid/pngtree-colorful-sport-shirt-mockup-front-and-back-view-generative-ai-png-image_11520387.png",
    imageAlt: "Colorful sport shirt mockup front and back view",
    colors: ["Red", "Blue", "Green"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 2,
    name: "Soccer Jersey",
    description: "A stylish soccer jersey with an abstract geometric pattern.",
    price: "₹299",
    rating: 4.0,
    category: "Yoga Mat",
    imageSrc: "https://png.pngtree.com/png-vector/20240309/ourmid/pngtree-soccer-jersey-mockup-abstract-geometric-pattern-sport-t-shirt-design-png-image_11905120.png",
    imageAlt: "Soccer jersey mockup with abstract geometric pattern",
    colors: ["Black", "Yellow"],
    sizes: ["M", "L", "XL"],
  },
  {
    id: 3,
    name: "Colorful Sports T-Shirts",
    description: "A collection of colorful sports t-shirts for every athlete.",
    price: "₹799",
    rating: 4.8,
    category: "Gym Bag",
    imageSrc: "https://5.imimg.com/data5/AR/PR/YN/SELLER-29862050/sports-t-shirts.png",
    imageAlt: "Various colorful sports t-shirts",
    colors: ["White", "Blue", "Orange"],
    sizes: ["S", "M", "L"],
  },
  {
    id: 4,
    name: "Multicolored Jersey",
    description: "A long sleeve multicolored textured jersey for a unique look.",
    price: "₹250",
    rating: 4.2,
    category: "Running Shoes",
    imageSrc: "https://static.vecteezy.com/system/resources/previews/051/043/910/non_2x/a-colorful-shirt-or-long-sleeve-jersey-with-a-multicolored-texture-design-isolated-on-a-transparent-background-png.png",
    imageAlt: "Long sleeve multicolored textured jersey isolated on transparent background",
    colors: ["Multicolor"],
    sizes: ["M", "L"],
  },
  {
    id: 5,
    name: "Colorful Sport Shirt",
    description: "A vibrant and breathable sport shirt perfect for workouts or casual wear.",
    price: "₹350",
    rating: 4.5,
    category: "Table Tennis",
    imageSrc: "https://png.pngtree.com/png-vector/20240131/ourmid/pngtree-colorful-sport-shirt-mockup-front-and-back-view-generative-ai-png-image_11520387.png",
    imageAlt: "Colorful sport shirt mockup front and back view",
    colors: ["Red", "Blue", "Green"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 6,
    name: "Soccer Jersey",
    description: "A stylish soccer jersey with an abstract geometric pattern.",
    price: "₹889",
    rating: 4.0,
    category: "Football",
    imageSrc: "https://png.pngtree.com/png-vector/20240309/ourmid/pngtree-soccer-jersey-mockup-abstract-geometric-pattern-sport-t-shirt-design-png-image_11905120.png",
    imageAlt: "Soccer jersey mockup with abstract geometric pattern",
    colors: ["Black", "Yellow"],
    sizes: ["M", "L", "XL"],
  },
  {
    id: 7,
    name: "Colorful Sports T-Shirts",
    description: "A collection of colorful sports t-shirts for every athlete.",
    price: "₹599",
    rating: 4.8,
    category: "Activewear",
    imageSrc: "https://5.imimg.com/data5/AR/PR/YN/SELLER-29862050/sports-t-shirts.png",
    imageAlt: "Various colorful sports t-shirts",
    colors: ["White", "Blue", "Orange"],
    sizes: ["S", "M", "L"],
  },
  {
    id: 8,
    name: "Multicolored Jersey",
    description: "A long sleeve multicolored textured jersey for a unique look.",
    price: "₹250",
    rating: 4.2,
    category: "Dumbbells",
    imageSrc: "https://static.vecteezy.com/system/resources/previews/051/043/910/non_2x/a-colorful-shirt-or-long-sleeve-jersey-with-a-multicolored-texture-design-isolated-on-a-transparent-background-png.png",
    imageAlt: "Long sleeve multicolored textured jersey isolated on transparent background",
    colors: ["Multicolor"],
    sizes: ["M", "L"],
  },
];

